# Generated by Django 5.2 on 2026-02-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('BANK', 'Virement Bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHECK', 'Chèque')], default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Non Payé'), ('PAID', 'Payé'), ('LATE', 'En Retard'), ('PARTIAL', 'Partiellement Payé')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='provider',
            field=models.CharField(choices=[('SNEL', 'SNEL'), ('REGIDESO', 'REGIDESO'), ('OTHER', 'Autre')], default='OTHER', max_length=50),
        ),
    ]
