# Generated by Django 5.2 on 2026-02-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_contract_alter_rent_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_active',
        ),
        migrations.AddField(
            model_name='contract',
            name='archive_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
