# Generated by Django 5.2 on 2026-01-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('type', models.CharField(help_text='Studio, F1, F2, etc.', max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, help_text='m2', max_digits=10, null=True)),
                ('standard_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('OCCUPIED', 'Occupé'), ('MAINTENANCE', 'En maintenance')], default='FREE', max_length=20)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='properties.gallery')),
            ],
        ),
    ]
