# Generated by Django 5.2 on 2026-02-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_gallery_manager_name_apartment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymanager',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallerymanager',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerymanager',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='properties.gallery'),
        ),
    ]
