# Generated by Django 5.2 on 2026-02-17 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_gallerymanager_end_date_gallerymanager_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymanager',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
